---
version: "3"

services:
        flask-app:
                 build:
                        context: ./
                        dockerfile: ./Dockerfile
                 image: pranjaladhikari/iss_tracker:2.0
                 ports:
                       - 5000:5000